//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Server.BeamableTest"/> </summary
    public sealed class BeamableTestClient : Beamable.Server.MicroserviceClient
    {
        
        /// <summary>
        /// Call the ServerCall method on the BeamableTest microservice
        /// <see cref="Beamable.Server.BeamableTest.ServerCall"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ServerCall()
        {
            string[] serializedFields = new string[0];
            return this.Request<Beamable.Common.Unit>("BeamableTest", "ServerCall", serializedFields);
        }
    }
}
